# This is a basic workflow to help you get started with Actions

name: Add Issue to project

on:
  issues:
    types: [opened]


jobs:
  track_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Add To GitHub Projects Beta
      uses: actions/add-to-project@v0.0.3
      with:
        # URL of the project to add issues to
        project-url: https://github.com/orgs/Azure/projects/94
        # A GitHub personal access token with write access to the project
        github-token: ${{ secrets.PERSONAL_TOKEN }}
      
      
    
