# This is a basic workflow to help you get started with Actions

name: Sync Labels

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Label Sync
        uses: EndBug/label-sync@v2.1.0
        with:
          # The repo to copy labels from (if not using a config file), in the 'owner/repo' format
          source-repo: Azure/azure-sdk-for-java false
          # Whether to only display the changes, without making them (useful if you're worried you're going to mess up)
          dry-run: true
